// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIAhXTY48lKLRpfsUWj3DdaTNIZST2fEs',
    appId: '1:711408185577:web:6e1b5d2b31f3ad8b4c4078',
    messagingSenderId: '711408185577',
    projectId: 'anaelmumin',
    authDomain: 'anaelmumin.firebaseapp.com',
    storageBucket: 'anaelmumin.firebasestorage.app',
    measurementId: 'G-4CQEV5CK2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDJQI3ZY6JIsFsj1fDQZD71YnBBQkGNEA',
    appId: '1:711408185577:android:a9579d0f7b8805264c4078',
    messagingSenderId: '711408185577',
    projectId: 'anaelmumin',
    storageBucket: 'anaelmumin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlYS8sWTzPE05MKUIQv4aZJ-HpWj2_woc',
    appId: '1:711408185577:ios:68219daefebb24614c4078',
    messagingSenderId: '711408185577',
    projectId: 'anaelmumin',
    storageBucket: 'anaelmumin.firebasestorage.app',
    iosBundleId: 'com.example.chatappTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlYS8sWTzPE05MKUIQv4aZJ-HpWj2_woc',
    appId: '1:711408185577:ios:68219daefebb24614c4078',
    messagingSenderId: '711408185577',
    projectId: 'anaelmumin',
    storageBucket: 'anaelmumin.firebasestorage.app',
    iosBundleId: 'com.example.chatappTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIAhXTY48lKLRpfsUWj3DdaTNIZST2fEs',
    appId: '1:711408185577:web:f4b52c112080a9bb4c4078',
    messagingSenderId: '711408185577',
    projectId: 'anaelmumin',
    authDomain: 'anaelmumin.firebaseapp.com',
    storageBucket: 'anaelmumin.firebasestorage.app',
    measurementId: 'G-6Y9RV8WMLL',
  );
}
